font:
  family: FiraCode
  style: Medium
  size: 8

window:
  opacity: 0.4
  paddin: 7
  margin: 6
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  # Normal colors
  normal:
    black:   '0x9f9f9f'
    red:     '0x6b6b6b'
    green:   '0xc4c4c4'
    yellow:  '0xb3b3b3'
    blue:    '0x999999'
    magenta: '0x717171'
    cyan:    '0x8a8a8a'
    white:   '0xf0f0f0'

  # Bright colors
  bright:
    black:   '0x404040'
    red:     '0x464646'
    green:   '0xf8f8f8'
    yellow:  '0xeeeeee'
    blue:    '0x7c7c7c'
    magenta: '0xadadad'
    cyan:    '0xc0c0c0'
    white:   '0x99ac9e'
